name: docker-pipline-sivarajesh
on: push
jobs:
  docker-job:
    runs-on: ubuntu-lastest
    steps:
      - name: Print your register number
        run: echo "Hello World - 22itl06"

        -name: Checkout
         uses: actions/checkout@v4

        
      - name: Docker Build
        run:  docker build -tsivarajeshc/ml-model-22itl06

      - name: Docker Images
        run:  docker images
