name: docker-pipeline-siva
on: push
jobs:
  docker-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print your Register Number
        run: echo "Hello World-22itlo6"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t csivarajesh/ml-model-22it006 .

      - name: Docker Images
        run: docker images
